### ISSUE TITLE
There is some issue with folder creation during running. Probably user right problems.

### ISSUE THREAD

**Issue by sebastianlange** [sebastianlange/Nature-Protocols-2018#32]
e.g. during pipeline: ava.lang.RuntimeException: java.lang.RuntimeException: Cannot create directory '/opt/snpEff-4.3T/data/GRCm38.86'

or during reference file creation:
INISHED --2019-05-05 22:49:25--
Total wall clock time: 26m 51s
Downloaded: 288 files, 12G in 26m 18s (7.59 MB/s)
parallel: This should not happen. You have found a bug.
Please contact <parallel@gnu.org> and include:
* The version number: 20161222
* The bugid: Cannot write to /home/docker/.parallel
* The command line being run
* The files being read (put the files on a webserver if they are big)

If you get the error on smaller/fewer files, please include those instead.
parallel: This should not happen. You have found a bug.
Please contact <parallel@gnu.org> and include:
* The version number: 20161222
* The bugid: Cannot write to /home/docker/.parallel
* The command line being run
* The files being read (put the files on a webserver if they are big)

If you get the error on smaller/fewer files, please include those instead.

**Comment by mfriedr** [comment]
Passiert das wenn Du die Pipeline mit USERID aufrufst?

**Comment by sebastianlange** [comment]
Ja!

On 7. May 2019, at 07:36, Mathias Friedrich <notifications@github.com> wrote:

Passiert das wenn Du die Pipeline mit USERID aufrufst?

**Comment by sebastianlange** [comment]
Snpeff Problem versuche ich abzufangen indem ich die Database vorher runterlase. Aber das paralllel Problem krieg ich nicht hin

On 7. May 2019, at 07:36, Mathias Friedrich <notifications@github.com> wrote:

Passiert das wenn Du die Pipeline mit USERID aufrufst? Chr. h

**Comment by mfriedr** [comment]
Wir haben nicht explizit ein homedir für den User docker angelegt, daher sollte keines existieren. Ist jetzt hoffentlich gefixt. Läuft die Pipeline jetzt durch?

**Comment by sebastianlange** [comment]
Bau es jetzt. Wissen wir frühestens heute Abend.
